language: node_js
node_js:
  - node
  - 15
  - 16
script:
  - echo "Running tests against $(node -v) ..."
  - npm test
jobs:
  include:
    - stage: lint
      script:
        - echo "lint start"
        - npm run lint
    - stage: github package release
      script:
        - echo "Deploying to github ..."
        - npm run build
      before_deploy: echo "//npm.pkg.github.com/:_authToken=\${GITHUB_TOKEN}" > .npmrc
      deploy:
        provider: npm
        edge: true
        registry: https://npm.pkg.github.com
        email: info@ateliee.com
        access: public
        on:
          branch: master
        api_key: $GITHUB_TOKEN
    - stage: npm package release
      script:
        - echo "Deploying to npm ..."
        - npm run build
      before_deploy: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      deploy:
        provider: npm
        edge: true
        email: info@ateliee.com
        access: public
        on:
          branch: master
        api_key: $NPM_TOKEN