name: Release

on:
  push:
    branches: [ master ]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      tag-created: ${{ steps.create-tag.outputs.tag-created }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get package version
      id: get-version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "version=v$VERSION" >> $GITHUB_OUTPUT
        echo "Package version: v$VERSION"
    
    - name: Check if tag exists
      id: check-tag
      run: |
        if git tag -l "${{ steps.get-version.outputs.version }}" | grep -q "${{ steps.get-version.outputs.version }}"; then
          echo "tag-exists=true" >> $GITHUB_OUTPUT
          echo "Tag ${{ steps.get-version.outputs.version }} already exists"
        else
          echo "tag-exists=false" >> $GITHUB_OUTPUT
          echo "Tag ${{ steps.get-version.outputs.version }} does not exist"
        fi
    
    - name: Create and push tag
      id: create-tag
      if: steps.check-tag.outputs.tag-exists == 'false'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "${{ steps.get-version.outputs.version }}" -m "Release ${{ steps.get-version.outputs.version }}"
        git push origin "${{ steps.get-version.outputs.version }}"
        echo "tag-created=true" >> $GITHUB_OUTPUT
        echo "Created and pushed tag: ${{ steps.get-version.outputs.version }}"

  github-package-release:
    runs-on: ubuntu-latest
    needs: create-tag
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@ateliee'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: |
        echo "Deploying to github ..."
        npm run build
    
    - name: Publish to GitHub Package Registry
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  npm-package-release:
    runs-on: ubuntu-latest
    needs: create-tag
    if: github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: |
        echo "Deploying to npm ..."
        npm run build
    
    - name: Publish to NPM Registry
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
